/*
 * PROJECT:    ReactOS Deutschland e.V. Helper Plugin
 * LICENSE:    GNU GPL v2 or any later version as published by the Free Software Foundation
 * COPYRIGHT:  Copyright 2010 ReactOS Deutschland e.V. <deutschland@reactos.org>
 * AUTHORS:    Colin Finck <colin@reactos.org>
 */

package org.reactos.ev.jameicaplugin.formatter;

import de.willuhn.datasource.rmi.DBIterator;
import de.willuhn.jameica.gui.formatter.Formatter;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import org.reactos.ev.jameicaplugin.rmi.Donation;

public class HTMLFormatter implements Formatter
{
    private static final DecimalFormat currencyFormat = (DecimalFormat) DecimalFormat.getInstance(Locale.US);
    private static final DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    private static final DateFormat yearFormat = new SimpleDateFormat("yyyy");

    static
    {
        currencyFormat.setMinimumFractionDigits(2);
        currencyFormat.setMaximumFractionDigits(2);
    }

    private String beginNewYear(String year)
    {
        String html = "<h3>" + year + "</h3>";

        html += "<table>";
        html += "<thead><tr>";
        html += "<th width=\"350\">Name</th>";
        html += "<th width=\"100\">Date</th>";
        html += "<th>Amount</th>";
        html += "</tr></thead>";
        html += "<tbody>";

        return html;
    }

    private String endYear()
    {
        return "</tbody></table>";
    }

    public String format(Object o)
    {
        String currentYear = "";
        DBIterator donationList = (DBIterator) o;
        String html = "<!-- Autogenerated by rosev_jameicaplugin -->";

        try
        {
            donationList.setOrder("ORDER BY date DESC");

            while (donationList.hasNext())
            {
                Donation d = (Donation) donationList.next();

                String year = yearFormat.format(d.getDate());
                if (!currentYear.equals(year))
                {
                    if (currentYear != "")
                        html += endYear();

                    html += beginNewYear(year);
                    currentYear = year;
                }

                html += "<tr>";

                if (d.isAnonymous())
                    html += "<td>Anonymous</td>";
                else
                    html += String.format("<td>%s</td>", d.getName());

                html += String.format("<td>%s</td>", dateFormat.format(d.getDate()));
                html += String.format("<td>%s %s</td>", d.getCurrency(), currencyFormat.format(d.getAmount()));
                html += "</tr>";
            }

            html += endYear();
        }
        catch (RemoteException e)
        {
            e.printStackTrace();
        }

        return html;
    }
}
