/*
 * PROJECT:    ReactOS Deutschland e.V. Helper Plugin
 * LICENSE:    GNU GPL v2 or any later version as published by the Free Software Foundation
 * COPYRIGHT:  Copyright 2010-2016 ReactOS Deutschland e.V. <deutschland@reactos.org>
 * AUTHORS:    Colin Finck <colin@reactos.org>
 */

package org.reactos.ev.jameicaplugin.formatter;

import de.willuhn.datasource.rmi.DBIterator;
import de.willuhn.jameica.gui.formatter.Formatter;
import de.willuhn.logging.Logger;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import org.reactos.ev.jameicaplugin.JameicaPlugin;
import org.reactos.ev.jameicaplugin.rmi.Donation;

public class HTMLFormatter implements Formatter
{
    private static final DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    private static final DateFormat yearFormat = new SimpleDateFormat("yyyy");

    private String beginNewYear(String year)
    {
        String html = "<h3>" + year + "</h3>";

        html += "<table>";
        html += "<thead><tr>";
        html += "<th width=\"350\">Name</th>";
        html += "<th width=\"100\">Date</th>";
        html += "<th>Amount</th>";
        html += "</tr></thead>";
        html += "<tbody>";

        return html;
    }

    private String endYear()
    {
        return "</tbody></table>";
    }

    @Override
    public String format(Object o)
    {
        String currentYear = "";

        @SuppressWarnings("unchecked")
        DBIterator<Donation> donationList = (DBIterator<Donation>) o;

        String html = "<!-- Autogenerated by rosev_jameicaplugin -->";
        html += dateFormat.format(new Date());
        html += "<br /><br />";

        try
        {
            // Output donations of the last 5 years.
            final Calendar cal = Calendar.getInstance();
            cal.set(Calendar.YEAR, cal.get(Calendar.YEAR) - 5);
            cal.set(Calendar.DAY_OF_YEAR, 1);
            donationList.addFilter("date >= ?", cal.getTime());

            donationList.setOrder("ORDER BY date DESC");

            while (donationList.hasNext())
            {
                Donation d = (Donation) donationList.next();

                String year = yearFormat.format(d.getDate());
                if (!currentYear.equals(year))
                {
                    if (currentYear != "")
                        html += endYear();

                    html += beginNewYear(year);
                    currentYear = year;
                }

                html += "<tr>";

                if (d.isAnonymous())
                    html += "<td>Anonymous</td>";
                else
                    html += String.format("<td>%s</td>", d.getName());

                html += String.format("<td>%s</td>", dateFormat.format(d.getDate()));
                html += String.format("<td>%s %s</td>", d.getCurrency(), JameicaPlugin.currencyFormatUS.format(d.getAmount()));
                html += "</tr>";
            }

            html += endYear();
        }
        catch (RemoteException e)
        {
            Logger.error("Error while formatting as HTML", e);
        }

        return html;
    }
}
